// flow-typed signature: 5559d97aaf526bbcbabcb99b36bc5e17
// flow-typed version: <<STUB>>/@commitlint/cli_v^16.2.1/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@commitlint/cli/cli' {
  declare module.exports: any;
}

declare module '@commitlint/cli/lib/cli-error' {
  declare module.exports: any;
}

declare module '@commitlint/cli/lib/cli' {
  declare module.exports: any;
}

declare module '@commitlint/cli/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@commitlint/cli/cli.js' {
  declare module.exports: $Exports<'@commitlint/cli/cli'>;
}
declare module '@commitlint/cli/index' {
  declare module.exports: $Exports<'@commitlint/cli'>;
}
declare module '@commitlint/cli/index.js' {
  declare module.exports: $Exports<'@commitlint/cli'>;
}
declare module '@commitlint/cli/lib/cli-error.js' {
  declare module.exports: $Exports<'@commitlint/cli/lib/cli-error'>;
}
declare module '@commitlint/cli/lib/cli.js' {
  declare module.exports: $Exports<'@commitlint/cli/lib/cli'>;
}
declare module '@commitlint/cli/lib/types.js' {
  declare module.exports: $Exports<'@commitlint/cli/lib/types'>;
}
