// flow-typed signature: b0ef0b5603354240750a6dfc16c63e8e
// flow-typed version: <<STUB>>/beaver-logger_v^3.0.17/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'beaver-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'beaver-logger' {
  declare module.exports: any;
}
