// flow-typed signature: d2cc9b17afa7167184224970c5ca84a0
// flow-typed version: <<STUB>>/belter_v1.0.123/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'belter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'belter' {
  declare module.exports: any;
}
