// flow-typed signature: bb8d29b0cbc622a4b90f7a13cfe32639
// flow-typed version: <<STUB>>/cross-domain-utils_v^2.0.16/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-domain-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-domain-utils' {
  declare module.exports: any;
}
