// flow-typed signature: 57aa71e139e70437a35b47668cdb234f
// flow-typed version: <<STUB>>/cross-domain-safe-weakmap_v^1.0.22/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-domain-safe-weakmap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-domain-safe-weakmap' {
  declare module.exports: any;
}
