// flow-typed signature: 944ea3c529d9a7f30af947e06e23ce6f
// flow-typed version: <<STUB>>/grumbler-scripts_v^2.0.19/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grumbler-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grumbler-scripts' {
  declare module.exports: any;
}
