// flow-typed signature: 2898222b48b89def740434d7b3668a66
// flow-typed version: <<STUB>>/hi-base32_v^0.5.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hi-base32'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hi-base32' {
  declare module.exports: any;
}
