// flow-typed signature: 879510e2b63c9ed0a1bead509d75e31c
// flow-typed version: <<STUB>>/husky_v^7.0.4/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'husky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'husky' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'husky/lib/bin' {
  declare module.exports: any;
}

declare module 'husky/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'husky/lib/bin.js' {
  declare module.exports: $Exports<'husky/lib/bin'>;
}
declare module 'husky/lib/index' {
  declare module.exports: $Exports<'husky/lib'>;
}
declare module 'husky/lib/index.js' {
  declare module.exports: $Exports<'husky/lib'>;
}
