// flow-typed signature: 2f18a21ae3c3d98267fdf998cc8111e8
// flow-typed version: <<STUB>>/post-robot_v^8.0.29/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'post-robot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'post-robot' {
  declare module.exports: any;
}
