// flow-typed signature: 570f5014289cb73342d1dd70c136bca1
// flow-typed version: <<STUB>>/standard-version_v^9.3.2/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'standard-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'standard-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'standard-version/bin/cli' {
  declare module.exports: any;
}

declare module 'standard-version/command' {
  declare module.exports: any;
}

declare module 'standard-version/defaults' {
  declare module.exports: any;
}

declare module 'standard-version/lib/checkpoint' {
  declare module.exports: any;
}

declare module 'standard-version/lib/configuration' {
  declare module.exports: any;
}

declare module 'standard-version/lib/format-commit-message' {
  declare module.exports: any;
}

declare module 'standard-version/lib/latest-semver-tag' {
  declare module.exports: any;
}

declare module 'standard-version/lib/lifecycles/bump' {
  declare module.exports: any;
}

declare module 'standard-version/lib/lifecycles/changelog' {
  declare module.exports: any;
}

declare module 'standard-version/lib/lifecycles/commit' {
  declare module.exports: any;
}

declare module 'standard-version/lib/lifecycles/tag' {
  declare module.exports: any;
}

declare module 'standard-version/lib/preset-loader' {
  declare module.exports: any;
}

declare module 'standard-version/lib/print-error' {
  declare module.exports: any;
}

declare module 'standard-version/lib/run-exec' {
  declare module.exports: any;
}

declare module 'standard-version/lib/run-execFile' {
  declare module.exports: any;
}

declare module 'standard-version/lib/run-lifecycle-script' {
  declare module.exports: any;
}

declare module 'standard-version/lib/updaters' {
  declare module.exports: any;
}

declare module 'standard-version/lib/updaters/types/json' {
  declare module.exports: any;
}

declare module 'standard-version/lib/updaters/types/plain-text' {
  declare module.exports: any;
}

declare module 'standard-version/lib/write-file' {
  declare module.exports: any;
}

declare module 'standard-version/test/config-files.spec' {
  declare module.exports: any;
}

declare module 'standard-version/test/core.spec' {
  declare module.exports: any;
}

declare module 'standard-version/test/git.spec' {
  declare module.exports: any;
}

declare module 'standard-version/test/mocks/updater/customer-updater' {
  declare module.exports: any;
}

declare module 'standard-version/test/preset.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'standard-version/bin/cli.js' {
  declare module.exports: $Exports<'standard-version/bin/cli'>;
}
declare module 'standard-version/command.js' {
  declare module.exports: $Exports<'standard-version/command'>;
}
declare module 'standard-version/defaults.js' {
  declare module.exports: $Exports<'standard-version/defaults'>;
}
declare module 'standard-version/index' {
  declare module.exports: $Exports<'standard-version'>;
}
declare module 'standard-version/index.js' {
  declare module.exports: $Exports<'standard-version'>;
}
declare module 'standard-version/lib/checkpoint.js' {
  declare module.exports: $Exports<'standard-version/lib/checkpoint'>;
}
declare module 'standard-version/lib/configuration.js' {
  declare module.exports: $Exports<'standard-version/lib/configuration'>;
}
declare module 'standard-version/lib/format-commit-message.js' {
  declare module.exports: $Exports<'standard-version/lib/format-commit-message'>;
}
declare module 'standard-version/lib/latest-semver-tag.js' {
  declare module.exports: $Exports<'standard-version/lib/latest-semver-tag'>;
}
declare module 'standard-version/lib/lifecycles/bump.js' {
  declare module.exports: $Exports<'standard-version/lib/lifecycles/bump'>;
}
declare module 'standard-version/lib/lifecycles/changelog.js' {
  declare module.exports: $Exports<'standard-version/lib/lifecycles/changelog'>;
}
declare module 'standard-version/lib/lifecycles/commit.js' {
  declare module.exports: $Exports<'standard-version/lib/lifecycles/commit'>;
}
declare module 'standard-version/lib/lifecycles/tag.js' {
  declare module.exports: $Exports<'standard-version/lib/lifecycles/tag'>;
}
declare module 'standard-version/lib/preset-loader.js' {
  declare module.exports: $Exports<'standard-version/lib/preset-loader'>;
}
declare module 'standard-version/lib/print-error.js' {
  declare module.exports: $Exports<'standard-version/lib/print-error'>;
}
declare module 'standard-version/lib/run-exec.js' {
  declare module.exports: $Exports<'standard-version/lib/run-exec'>;
}
declare module 'standard-version/lib/run-execFile.js' {
  declare module.exports: $Exports<'standard-version/lib/run-execFile'>;
}
declare module 'standard-version/lib/run-lifecycle-script.js' {
  declare module.exports: $Exports<'standard-version/lib/run-lifecycle-script'>;
}
declare module 'standard-version/lib/updaters/index' {
  declare module.exports: $Exports<'standard-version/lib/updaters'>;
}
declare module 'standard-version/lib/updaters/index.js' {
  declare module.exports: $Exports<'standard-version/lib/updaters'>;
}
declare module 'standard-version/lib/updaters/types/json.js' {
  declare module.exports: $Exports<'standard-version/lib/updaters/types/json'>;
}
declare module 'standard-version/lib/updaters/types/plain-text.js' {
  declare module.exports: $Exports<'standard-version/lib/updaters/types/plain-text'>;
}
declare module 'standard-version/lib/write-file.js' {
  declare module.exports: $Exports<'standard-version/lib/write-file'>;
}
declare module 'standard-version/test/config-files.spec.js' {
  declare module.exports: $Exports<'standard-version/test/config-files.spec'>;
}
declare module 'standard-version/test/core.spec.js' {
  declare module.exports: $Exports<'standard-version/test/core.spec'>;
}
declare module 'standard-version/test/git.spec.js' {
  declare module.exports: $Exports<'standard-version/test/git.spec'>;
}
declare module 'standard-version/test/mocks/updater/customer-updater.js' {
  declare module.exports: $Exports<'standard-version/test/mocks/updater/customer-updater'>;
}
declare module 'standard-version/test/preset.spec.js' {
  declare module.exports: $Exports<'standard-version/test/preset.spec'>;
}
