// flow-typed signature: 3fa02b9dba4aa7fbad43a9b1b9a07c64
// flow-typed version: <<STUB>>/zalgo-promise_v^1.0.34/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zalgo-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zalgo-promise' {
  declare module.exports: any;
}
