// flow-typed signature: 1d9a51a538917baa9335b2b04ae1946b
// flow-typed version: <<STUB>>/@krakenjs/belter_v^2.0.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/belter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@krakenjs/belter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@krakenjs/belter/dist/belter' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/belter.min' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/constants' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/css' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/decorators' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/device' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/dom' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/experiment' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/global' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/http' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/index.flow' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/screenHeights' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/storage' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/storage.test' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/test' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/types' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/dist/module/util' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/constants' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/css' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/decorators' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/device' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/dom' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/experiment' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/global' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/http' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/index.flow' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/screenHeights' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/storage' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/storage.test' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/test' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/types' {
  declare module.exports: any;
}

declare module '@krakenjs/belter/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@krakenjs/belter/dist/belter.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/belter'>;
}
declare module '@krakenjs/belter/dist/belter.min.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/belter.min'>;
}
declare module '@krakenjs/belter/dist/module/constants.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/constants'>;
}
declare module '@krakenjs/belter/dist/module/css.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/css'>;
}
declare module '@krakenjs/belter/dist/module/decorators.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/decorators'>;
}
declare module '@krakenjs/belter/dist/module/device.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/device'>;
}
declare module '@krakenjs/belter/dist/module/dom.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/dom'>;
}
declare module '@krakenjs/belter/dist/module/experiment.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/experiment'>;
}
declare module '@krakenjs/belter/dist/module/global.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/global'>;
}
declare module '@krakenjs/belter/dist/module/http.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/http'>;
}
declare module '@krakenjs/belter/dist/module/index.flow.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/index.flow'>;
}
declare module '@krakenjs/belter/dist/module/index' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module'>;
}
declare module '@krakenjs/belter/dist/module/index.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module'>;
}
declare module '@krakenjs/belter/dist/module/screenHeights.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/screenHeights'>;
}
declare module '@krakenjs/belter/dist/module/storage.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/storage'>;
}
declare module '@krakenjs/belter/dist/module/storage.test.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/storage.test'>;
}
declare module '@krakenjs/belter/dist/module/test.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/test'>;
}
declare module '@krakenjs/belter/dist/module/types.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/types'>;
}
declare module '@krakenjs/belter/dist/module/util.js' {
  declare module.exports: $Exports<'@krakenjs/belter/dist/module/util'>;
}
declare module '@krakenjs/belter/index' {
  declare module.exports: $Exports<'@krakenjs/belter'>;
}
declare module '@krakenjs/belter/index.js' {
  declare module.exports: $Exports<'@krakenjs/belter'>;
}
declare module '@krakenjs/belter/src/constants.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/constants'>;
}
declare module '@krakenjs/belter/src/css.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/css'>;
}
declare module '@krakenjs/belter/src/decorators.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/decorators'>;
}
declare module '@krakenjs/belter/src/device.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/device'>;
}
declare module '@krakenjs/belter/src/dom.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/dom'>;
}
declare module '@krakenjs/belter/src/experiment.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/experiment'>;
}
declare module '@krakenjs/belter/src/global.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/global'>;
}
declare module '@krakenjs/belter/src/http.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/http'>;
}
declare module '@krakenjs/belter/src/index.flow.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/index.flow'>;
}
declare module '@krakenjs/belter/src/index' {
  declare module.exports: $Exports<'@krakenjs/belter/src'>;
}
declare module '@krakenjs/belter/src/index.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src'>;
}
declare module '@krakenjs/belter/src/screenHeights.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/screenHeights'>;
}
declare module '@krakenjs/belter/src/storage.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/storage'>;
}
declare module '@krakenjs/belter/src/storage.test.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/storage.test'>;
}
declare module '@krakenjs/belter/src/test.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/test'>;
}
declare module '@krakenjs/belter/src/types.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/types'>;
}
declare module '@krakenjs/belter/src/util.js' {
  declare module.exports: $Exports<'@krakenjs/belter/src/util'>;
}
