// flow-typed signature: 1b384d8a481c18b578d4eb7f1866aefd
// flow-typed version: <<STUB>>/@krakenjs/cross-domain-utils_v^3.0.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/cross-domain-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@krakenjs/cross-domain-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@krakenjs/cross-domain-utils/dist/cross-domain-utils' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/dist/cross-domain-utils.min' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/dist/module/constants' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/dist/module/index.flow' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/dist/module' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/dist/module/types' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/dist/module/util' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/dist/module/utils' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/src/constants' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/src/index.flow' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/src' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/src/types' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/src/util' {
  declare module.exports: any;
}

declare module '@krakenjs/cross-domain-utils/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@krakenjs/cross-domain-utils/dist/cross-domain-utils.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/dist/cross-domain-utils'>;
}
declare module '@krakenjs/cross-domain-utils/dist/cross-domain-utils.min.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/dist/cross-domain-utils.min'>;
}
declare module '@krakenjs/cross-domain-utils/dist/module/constants.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/dist/module/constants'>;
}
declare module '@krakenjs/cross-domain-utils/dist/module/index.flow.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/dist/module/index.flow'>;
}
declare module '@krakenjs/cross-domain-utils/dist/module/index' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/dist/module'>;
}
declare module '@krakenjs/cross-domain-utils/dist/module/index.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/dist/module'>;
}
declare module '@krakenjs/cross-domain-utils/dist/module/types.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/dist/module/types'>;
}
declare module '@krakenjs/cross-domain-utils/dist/module/util.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/dist/module/util'>;
}
declare module '@krakenjs/cross-domain-utils/dist/module/utils.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/dist/module/utils'>;
}
declare module '@krakenjs/cross-domain-utils/src/constants.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/src/constants'>;
}
declare module '@krakenjs/cross-domain-utils/src/index.flow.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/src/index.flow'>;
}
declare module '@krakenjs/cross-domain-utils/src/index' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/src'>;
}
declare module '@krakenjs/cross-domain-utils/src/index.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/src'>;
}
declare module '@krakenjs/cross-domain-utils/src/types.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/src/types'>;
}
declare module '@krakenjs/cross-domain-utils/src/util.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/src/util'>;
}
declare module '@krakenjs/cross-domain-utils/src/utils.js' {
  declare module.exports: $Exports<'@krakenjs/cross-domain-utils/src/utils'>;
}
