// flow-typed signature: 7ec2f9ff984b201918fcd9678837db06
// flow-typed version: <<STUB>>/@krakenjs/grumbler-scripts_v^8.0.4/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/grumbler-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@krakenjs/grumbler-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@krakenjs/grumbler-scripts/config/karma.conf' {
  declare module.exports: any;
}

declare module '@krakenjs/grumbler-scripts/config/webpack.config' {
  declare module.exports: any;
}

declare module '@krakenjs/grumbler-scripts/test/component' {
  declare module.exports: any;
}

declare module '@krakenjs/grumbler-scripts/test/dependency' {
  declare module.exports: any;
}

declare module '@krakenjs/grumbler-scripts/test/module' {
  declare module.exports: any;
}

declare module '@krakenjs/grumbler-scripts/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@krakenjs/grumbler-scripts/config/karma.conf.js' {
  declare module.exports: $Exports<'@krakenjs/grumbler-scripts/config/karma.conf'>;
}
declare module '@krakenjs/grumbler-scripts/config/webpack.config.js' {
  declare module.exports: $Exports<'@krakenjs/grumbler-scripts/config/webpack.config'>;
}
declare module '@krakenjs/grumbler-scripts/test/component.jsx' {
  declare module.exports: $Exports<'@krakenjs/grumbler-scripts/test/component'>;
}
declare module '@krakenjs/grumbler-scripts/test/dependency.js' {
  declare module.exports: $Exports<'@krakenjs/grumbler-scripts/test/dependency'>;
}
declare module '@krakenjs/grumbler-scripts/test/module.js' {
  declare module.exports: $Exports<'@krakenjs/grumbler-scripts/test/module'>;
}
declare module '@krakenjs/grumbler-scripts/webpack.config.js' {
  declare module.exports: $Exports<'@krakenjs/grumbler-scripts/webpack.config'>;
}
