// flow-typed signature: e3879a2c640bc8421f798cb70cce7477
// flow-typed version: <<STUB>>/@krakenjs/jsx-pragmatic_v^3.0.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/jsx-pragmatic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@krakenjs/jsx-pragmatic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@krakenjs/jsx-pragmatic/dist/jsx-pragmatic-demo' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/jsx-pragmatic' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/jsx-pragmatic.min' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/component' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/component/regex' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/component/style' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/constants' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/node' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/dom' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/html' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/renderers' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/preact' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/react' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/regex' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/text' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/types' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/dist/module/util' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/component' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/component/regex' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/component/style' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/constants' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/node' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/renderers/dom' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/renderers/html' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/renderers' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/renderers/preact' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/renderers/react' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/renderers/regex' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/renderers/text' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/types' {
  declare module.exports: any;
}

declare module '@krakenjs/jsx-pragmatic/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@krakenjs/jsx-pragmatic/dist/jsx-pragmatic-demo.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/jsx-pragmatic-demo'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/jsx-pragmatic.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/jsx-pragmatic'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/jsx-pragmatic.min.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/jsx-pragmatic.min'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/component/index' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/component'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/component/index.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/component'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/component/regex.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/component/regex'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/component/style.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/component/style'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/constants.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/constants'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/index' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/index.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/node.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/node'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/dom.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/renderers/dom'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/html.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/renderers/html'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/index' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/renderers'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/index.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/renderers'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/preact.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/renderers/preact'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/react.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/renderers/react'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/regex.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/renderers/regex'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/renderers/text.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/renderers/text'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/types.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/types'>;
}
declare module '@krakenjs/jsx-pragmatic/dist/module/util.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/dist/module/util'>;
}
declare module '@krakenjs/jsx-pragmatic/index' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic'>;
}
declare module '@krakenjs/jsx-pragmatic/index.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic'>;
}
declare module '@krakenjs/jsx-pragmatic/src/component/index' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/component'>;
}
declare module '@krakenjs/jsx-pragmatic/src/component/index.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/component'>;
}
declare module '@krakenjs/jsx-pragmatic/src/component/regex.jsx' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/component/regex'>;
}
declare module '@krakenjs/jsx-pragmatic/src/component/style.jsx' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/component/style'>;
}
declare module '@krakenjs/jsx-pragmatic/src/constants.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/constants'>;
}
declare module '@krakenjs/jsx-pragmatic/src/index' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src'>;
}
declare module '@krakenjs/jsx-pragmatic/src/index.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src'>;
}
declare module '@krakenjs/jsx-pragmatic/src/node.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/node'>;
}
declare module '@krakenjs/jsx-pragmatic/src/renderers/dom.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/renderers/dom'>;
}
declare module '@krakenjs/jsx-pragmatic/src/renderers/html.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/renderers/html'>;
}
declare module '@krakenjs/jsx-pragmatic/src/renderers/index' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/renderers'>;
}
declare module '@krakenjs/jsx-pragmatic/src/renderers/index.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/renderers'>;
}
declare module '@krakenjs/jsx-pragmatic/src/renderers/preact.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/renderers/preact'>;
}
declare module '@krakenjs/jsx-pragmatic/src/renderers/react.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/renderers/react'>;
}
declare module '@krakenjs/jsx-pragmatic/src/renderers/regex.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/renderers/regex'>;
}
declare module '@krakenjs/jsx-pragmatic/src/renderers/text.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/renderers/text'>;
}
declare module '@krakenjs/jsx-pragmatic/src/types.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/types'>;
}
declare module '@krakenjs/jsx-pragmatic/src/util.js' {
  declare module.exports: $Exports<'@krakenjs/jsx-pragmatic/src/util'>;
}
