// flow-typed signature: 18f28813f8bef0fbfc11f18b89116082
// flow-typed version: <<STUB>>/@krakenjs/post-robot_v^11.0.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/post-robot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@krakenjs/post-robot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@krakenjs/post-robot/dist/module/bridge/bridge' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/bridge/child' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/bridge/common' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/bridge' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/bridge/parent' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/bridge/setup' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/clean' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/conf/config' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/conf/constants' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/conf' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/declarations' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/drivers' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/drivers/listeners' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/drivers/receive' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/drivers/receive/types' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/drivers/send' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/drivers/send/strategies' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/drivers/types' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/global' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/lib/compat' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/lib/hello' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/lib' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/lib/windows' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/public' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/public/on' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/public/send' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/serialize/function' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/serialize' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/serialize/promise' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/serialize/serialize' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/serialize/window' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/setup' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/module/types' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/post-robot.ie' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/post-robot.ie.min' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/post-robot' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/dist/post-robot.min' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/globals' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/bridge/bridge' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/bridge/child' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/bridge/common' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/bridge' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/bridge/parent' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/bridge/setup' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/clean' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/conf/config' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/conf/constants' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/conf' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/declarations' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/drivers' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/drivers/listeners' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/drivers/receive' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/drivers/receive/types' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/drivers/send' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/drivers/send/strategies' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/drivers/types' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/global' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/lib/compat' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/lib/hello' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/lib' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/lib/windows' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/public' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/public/on' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/public/send' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/serialize/function' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/serialize' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/serialize/promise' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/serialize/serialize' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/serialize/window' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/setup' {
  declare module.exports: any;
}

declare module '@krakenjs/post-robot/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@krakenjs/post-robot/dist/module/bridge/bridge.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/bridge/bridge'>;
}
declare module '@krakenjs/post-robot/dist/module/bridge/child.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/bridge/child'>;
}
declare module '@krakenjs/post-robot/dist/module/bridge/common.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/bridge/common'>;
}
declare module '@krakenjs/post-robot/dist/module/bridge/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/bridge'>;
}
declare module '@krakenjs/post-robot/dist/module/bridge/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/bridge'>;
}
declare module '@krakenjs/post-robot/dist/module/bridge/parent.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/bridge/parent'>;
}
declare module '@krakenjs/post-robot/dist/module/bridge/setup.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/bridge/setup'>;
}
declare module '@krakenjs/post-robot/dist/module/clean.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/clean'>;
}
declare module '@krakenjs/post-robot/dist/module/conf/config.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/conf/config'>;
}
declare module '@krakenjs/post-robot/dist/module/conf/constants.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/conf/constants'>;
}
declare module '@krakenjs/post-robot/dist/module/conf/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/conf'>;
}
declare module '@krakenjs/post-robot/dist/module/conf/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/conf'>;
}
declare module '@krakenjs/post-robot/dist/module/declarations.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/declarations'>;
}
declare module '@krakenjs/post-robot/dist/module/drivers/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/drivers'>;
}
declare module '@krakenjs/post-robot/dist/module/drivers/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/drivers'>;
}
declare module '@krakenjs/post-robot/dist/module/drivers/listeners.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/drivers/listeners'>;
}
declare module '@krakenjs/post-robot/dist/module/drivers/receive/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/drivers/receive'>;
}
declare module '@krakenjs/post-robot/dist/module/drivers/receive/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/drivers/receive'>;
}
declare module '@krakenjs/post-robot/dist/module/drivers/receive/types.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/drivers/receive/types'>;
}
declare module '@krakenjs/post-robot/dist/module/drivers/send/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/drivers/send'>;
}
declare module '@krakenjs/post-robot/dist/module/drivers/send/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/drivers/send'>;
}
declare module '@krakenjs/post-robot/dist/module/drivers/send/strategies.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/drivers/send/strategies'>;
}
declare module '@krakenjs/post-robot/dist/module/drivers/types.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/drivers/types'>;
}
declare module '@krakenjs/post-robot/dist/module/global.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/global'>;
}
declare module '@krakenjs/post-robot/dist/module/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module'>;
}
declare module '@krakenjs/post-robot/dist/module/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module'>;
}
declare module '@krakenjs/post-robot/dist/module/lib/compat.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/lib/compat'>;
}
declare module '@krakenjs/post-robot/dist/module/lib/hello.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/lib/hello'>;
}
declare module '@krakenjs/post-robot/dist/module/lib/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/lib'>;
}
declare module '@krakenjs/post-robot/dist/module/lib/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/lib'>;
}
declare module '@krakenjs/post-robot/dist/module/lib/windows.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/lib/windows'>;
}
declare module '@krakenjs/post-robot/dist/module/public/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/public'>;
}
declare module '@krakenjs/post-robot/dist/module/public/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/public'>;
}
declare module '@krakenjs/post-robot/dist/module/public/on.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/public/on'>;
}
declare module '@krakenjs/post-robot/dist/module/public/send.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/public/send'>;
}
declare module '@krakenjs/post-robot/dist/module/serialize/function.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/serialize/function'>;
}
declare module '@krakenjs/post-robot/dist/module/serialize/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/serialize'>;
}
declare module '@krakenjs/post-robot/dist/module/serialize/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/serialize'>;
}
declare module '@krakenjs/post-robot/dist/module/serialize/promise.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/serialize/promise'>;
}
declare module '@krakenjs/post-robot/dist/module/serialize/serialize.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/serialize/serialize'>;
}
declare module '@krakenjs/post-robot/dist/module/serialize/window.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/serialize/window'>;
}
declare module '@krakenjs/post-robot/dist/module/setup.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/setup'>;
}
declare module '@krakenjs/post-robot/dist/module/types.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/module/types'>;
}
declare module '@krakenjs/post-robot/dist/post-robot.ie.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/post-robot.ie'>;
}
declare module '@krakenjs/post-robot/dist/post-robot.ie.min.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/post-robot.ie.min'>;
}
declare module '@krakenjs/post-robot/dist/post-robot.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/post-robot'>;
}
declare module '@krakenjs/post-robot/dist/post-robot.min.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/dist/post-robot.min'>;
}
declare module '@krakenjs/post-robot/globals.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/globals'>;
}
declare module '@krakenjs/post-robot/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot'>;
}
declare module '@krakenjs/post-robot/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot'>;
}
declare module '@krakenjs/post-robot/src/bridge/bridge.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/bridge/bridge'>;
}
declare module '@krakenjs/post-robot/src/bridge/child.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/bridge/child'>;
}
declare module '@krakenjs/post-robot/src/bridge/common.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/bridge/common'>;
}
declare module '@krakenjs/post-robot/src/bridge/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/bridge'>;
}
declare module '@krakenjs/post-robot/src/bridge/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/bridge'>;
}
declare module '@krakenjs/post-robot/src/bridge/parent.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/bridge/parent'>;
}
declare module '@krakenjs/post-robot/src/bridge/setup.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/bridge/setup'>;
}
declare module '@krakenjs/post-robot/src/clean.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/clean'>;
}
declare module '@krakenjs/post-robot/src/conf/config.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/conf/config'>;
}
declare module '@krakenjs/post-robot/src/conf/constants.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/conf/constants'>;
}
declare module '@krakenjs/post-robot/src/conf/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/conf'>;
}
declare module '@krakenjs/post-robot/src/conf/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/conf'>;
}
declare module '@krakenjs/post-robot/src/declarations.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/declarations'>;
}
declare module '@krakenjs/post-robot/src/drivers/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/drivers'>;
}
declare module '@krakenjs/post-robot/src/drivers/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/drivers'>;
}
declare module '@krakenjs/post-robot/src/drivers/listeners.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/drivers/listeners'>;
}
declare module '@krakenjs/post-robot/src/drivers/receive/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/drivers/receive'>;
}
declare module '@krakenjs/post-robot/src/drivers/receive/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/drivers/receive'>;
}
declare module '@krakenjs/post-robot/src/drivers/receive/types.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/drivers/receive/types'>;
}
declare module '@krakenjs/post-robot/src/drivers/send/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/drivers/send'>;
}
declare module '@krakenjs/post-robot/src/drivers/send/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/drivers/send'>;
}
declare module '@krakenjs/post-robot/src/drivers/send/strategies.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/drivers/send/strategies'>;
}
declare module '@krakenjs/post-robot/src/drivers/types.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/drivers/types'>;
}
declare module '@krakenjs/post-robot/src/global.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/global'>;
}
declare module '@krakenjs/post-robot/src/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src'>;
}
declare module '@krakenjs/post-robot/src/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src'>;
}
declare module '@krakenjs/post-robot/src/lib/compat.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/lib/compat'>;
}
declare module '@krakenjs/post-robot/src/lib/hello.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/lib/hello'>;
}
declare module '@krakenjs/post-robot/src/lib/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/lib'>;
}
declare module '@krakenjs/post-robot/src/lib/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/lib'>;
}
declare module '@krakenjs/post-robot/src/lib/windows.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/lib/windows'>;
}
declare module '@krakenjs/post-robot/src/public/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/public'>;
}
declare module '@krakenjs/post-robot/src/public/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/public'>;
}
declare module '@krakenjs/post-robot/src/public/on.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/public/on'>;
}
declare module '@krakenjs/post-robot/src/public/send.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/public/send'>;
}
declare module '@krakenjs/post-robot/src/serialize/function.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/serialize/function'>;
}
declare module '@krakenjs/post-robot/src/serialize/index' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/serialize'>;
}
declare module '@krakenjs/post-robot/src/serialize/index.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/serialize'>;
}
declare module '@krakenjs/post-robot/src/serialize/promise.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/serialize/promise'>;
}
declare module '@krakenjs/post-robot/src/serialize/serialize.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/serialize/serialize'>;
}
declare module '@krakenjs/post-robot/src/serialize/window.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/serialize/window'>;
}
declare module '@krakenjs/post-robot/src/setup.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/setup'>;
}
declare module '@krakenjs/post-robot/src/types.js' {
  declare module.exports: $Exports<'@krakenjs/post-robot/src/types'>;
}
