// flow-typed signature: a31bde17276864ac955bb0ae5d9ebb5f
// flow-typed version: <<STUB>>/@krakenjs/zalgo-promise_v^2.0.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/zalgo-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@krakenjs/zalgo-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@krakenjs/zalgo-promise/dist/module/exceptions' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/dist/module/export' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/dist/module/flush' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/dist/module' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/dist/module/promise' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/dist/module/types' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/dist/module/utils' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/dist/zalgo-promise' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/dist/zalgo-promise.min' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/src/exceptions' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/src/export' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/src/flush' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/src' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/src/promise' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/src/types' {
  declare module.exports: any;
}

declare module '@krakenjs/zalgo-promise/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@krakenjs/zalgo-promise/dist/module/exceptions.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/dist/module/exceptions'>;
}
declare module '@krakenjs/zalgo-promise/dist/module/export.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/dist/module/export'>;
}
declare module '@krakenjs/zalgo-promise/dist/module/flush.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/dist/module/flush'>;
}
declare module '@krakenjs/zalgo-promise/dist/module/index' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/dist/module'>;
}
declare module '@krakenjs/zalgo-promise/dist/module/index.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/dist/module'>;
}
declare module '@krakenjs/zalgo-promise/dist/module/promise.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/dist/module/promise'>;
}
declare module '@krakenjs/zalgo-promise/dist/module/types.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/dist/module/types'>;
}
declare module '@krakenjs/zalgo-promise/dist/module/utils.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/dist/module/utils'>;
}
declare module '@krakenjs/zalgo-promise/dist/zalgo-promise.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/dist/zalgo-promise'>;
}
declare module '@krakenjs/zalgo-promise/dist/zalgo-promise.min.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/dist/zalgo-promise.min'>;
}
declare module '@krakenjs/zalgo-promise/index' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise'>;
}
declare module '@krakenjs/zalgo-promise/index.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise'>;
}
declare module '@krakenjs/zalgo-promise/src/exceptions.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/src/exceptions'>;
}
declare module '@krakenjs/zalgo-promise/src/export.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/src/export'>;
}
declare module '@krakenjs/zalgo-promise/src/flush.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/src/flush'>;
}
declare module '@krakenjs/zalgo-promise/src/index' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/src'>;
}
declare module '@krakenjs/zalgo-promise/src/index.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/src'>;
}
declare module '@krakenjs/zalgo-promise/src/promise.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/src/promise'>;
}
declare module '@krakenjs/zalgo-promise/src/types.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/src/types'>;
}
declare module '@krakenjs/zalgo-promise/src/utils.js' {
  declare module.exports: $Exports<'@krakenjs/zalgo-promise/src/utils'>;
}
