
import xcomponent from 'src/index';
import postRobot from 'post-robot/src';

import { testComponent, testComponent3 } from '../component';
import { b64encode } from 'src/lib';

let component;

afterEach(() => {
    if (component) {
        component.destroy();
        component = null;
    }
});

describe('xcomponent error cases', () => {

    it('should error out when window.open returns a closed window', done => {

        let windowOpen = window.open;

        window.open = () => {
            return {
                closed: true,
                close() {}
            };
        };

        component = testComponent.init({
            onEnter: done
        });

        component.renderPopup().catch(err => {
            console.log(err.message, err.stack);
            assert.isTrue(err instanceof xcomponent.PopupOpenError, 'Expected PopupOpenError when popup is not opened');
            window.open = windowOpen;
            done();
        });
    });

    it.skip('should enter a component, throw an error, and return a new error to the parent without the original stack', done => {

        component = testComponent.init({

            onError(err) {
                assert.isTrue(err.message.indexOf('xxxxx') === -1, 'Expected error to not contain original error');
                done();
            }

        });


        component.renderLightbox();

        postRobot.once('init', () => 'attachTestComponentAndThrowRegularError');
    });

    it('should enter a component, throw an integration error, and return the error to the parent with the original stack', done => {

        component = testComponent.init({

            onError(err) {
                assert.isTrue(err.message.indexOf('xxxxx') !== -1, 'Expected error to contain original error');
                done();
            }

        });


        component.renderLightbox();

        postRobot.once('init', () => 'attachTestComponentAndThrowIntegrationError');
    });

    it('should enter a component and timeout, then call onTimeout', done => {

        component = testComponent.init({
            timeout: 1,
            onTimeout() {
                done();
            }
        });

        component.renderLightbox();
    });

    it('should enter a component and timeout, then call onError in the absense of onTimeout', done => {

        component = testComponent.init({
            timeout: 1,
            onError() {
                done();
            }
        });

        component.renderLightbox();
    });

    it('should enter a component and timeout, then log an error in the absense of onTimeout and onError', done => {

        let console = window.console;

        window.console = {
            error() {
                window.console = console;
                done();
            }
        };

        component = testComponent.init({
            timeout: 1
        });

        component.renderLightbox();
    });

    it('should enter a component and error out when the page name is not valid', done => {

        window.open('/base/test/child.htm', 'INVALIDNAME');

        postRobot.once('init', () => 'attachTestComponentWithInvalidName');
        postRobot.once('complete', () => done());
    });

    it('should enter a component and error out when the page name is not generated by xcomponent', done => {

        window.open('/base/test/child.htm', b64encode('{}'));

        postRobot.once('init', () => 'attachTestComponentWithInvalidName');
        postRobot.once('complete', () => done());
    });

    it('should try to enter a singleton component twice and error out', done => {

        component = testComponent.init({
            onEnter() {
                try {
                    testComponent.init();
                } catch (err) {
                    done();
                }
            }
        });

        component.renderLightbox();

        postRobot.once('init', () => 'attachTestComponent');
    });

    it('should try to render a component twice and error out', done => {

        component = testComponent.init();

        component.render().then(() => {
            component.render().catch(() => {
                done();
            });
        });

        postRobot.once('init', () => 'attachTestComponent');
    });

    it('should try to render a component to an unsupported context and error out', done => {

        component = testComponent3.init();

        component.render(null, 'moo').catch(() => {
            done();
        });
    });

    it('should try to render a component with a specified element when iframe mode is not supported', done => {

        component = testComponent3.init();

        component.render(document.body).catch(() => {
            done();
        });
    });

    it('should try to render to when iframe is the only available option but no element is passed', done => {

        let originalDefaultContext = testComponent.defaultContext;
        let originalContexts = testComponent.contexts;

        delete testComponent.defaultContext;
        testComponent.contexts = {
            popup: false,
            lightbox: false,
            iframe: true
        };

        component = testComponent.init();

        component.render().catch(err => {
            assert.ok(err);
            testComponent.defaultContext = originalDefaultContext;
            testComponent.contexts = originalContexts;
            done();
        });
    });

    it('should call onclose when a popup is closed by someone other than xcomponent', done => {

        component = testComponent.init({

            onEnter() {
                setTimeout(() => {
                    this.window.close();
                });
            },

            onClose() {
                done();
            }
        });

        component.renderPopup();

        postRobot.once('init', () => 'attachTestComponent');
    });

    it('should call onclose when a lightbox is closed by someone other than xcomponent', done => {

        component = testComponent.init({

            onEnter() {
                setTimeout(() => {
                    this.iframe.parentNode.removeChild(this.iframe);
                });
            },

            onClose() {
                done();
            }
        });

        component.renderLightbox();

        postRobot.once('init', () => 'attachTestComponent');
    });

    it('should error on the child when trying to attach a different component to that which was rendered', done => {

        component = testComponent.init({
            onEnter() {
                done();
            }
        });

        component.renderLightbox();

        postRobot.once('init', () => 'attachTestComponent4AndCallCompleteOnError');
        postRobot.once('complete', () => done());
    });
});